### PR TITLE
Remove Ruby 1.8 (+ update SimpleCov dependency to 0.15.1)

### PR DESCRIPTION
**Pull request by tagliala**
Didn't get an answer on this: #112

This PR:
- Drops Ruby 1.8 support
- Update SimpleCov to 0.15.1
- Fix tests against Ruby 1.9.3
- Update Ruby version to 2.4.2
- Update Thor dependency to `~> 0.20.0`
- Test against latest Ruby versions

### CODE REVIEW

**Comment by tagliala** [comment]
This PR includes #124

**Comment by tagliala** [comment]
Hi, I've released a gem which includes this PR

You can find it at https://github.com/tagliala/coveralls-ruby-reborn

You just need to change your Gemfile:

```rb
gem 'coveralls_reborn', '~> 0.9.0', require: false
```

**Comment by tagliala** [comment]
@nijikon hi,

please take a look at my fork: https://github.com/tagliala/coveralls-ruby-reborn

I've just released a 0.10.0 version which includes this PR and also drops support for Ruby 1.9 and 2.0

It should also ease future development, because I've bumped all development dependencies and standardized code guidelines with RuboCop and RuboCop RSpec

I hope that all the news commit I've pushed to coveralls_reborn's repo will be merged into this gem

**Comment by apanzerj** [comment]
@nickmerwin is this good to merge??

**Pull request closed without merging**
