### PR TITLE
Remove RestClient dependency

### PR DESCRIPTION
**Pull request by mlarraz**
I'd like to whittle down the list of this gem's dependencies to make it easier to use anywhere.

This change, in particular, will help with some specific apps that are stuck on older versions of rest-client.

### CODE REVIEW

**Comment by kbrock** [comment]
Is there a reason you added `addressable`?

**Comment by mlarraz** [comment]
Yes, a separate issue. `webmock` requires `addressable (>= 2.3.6)`, but `~> 2.3.8` is necessary to work on Ruby 1.8. This isn't a problem on Travis because the bundle is cached, but affects anyone doing a fresh install on Ruby 1.8.

**Comment by nickmerwin** [comment]
Thanks @mlarraz, could you take a look at these warnings in the specs?

```bash
/Users/nickmerwin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/request_body_diff.rb:20: warning: private attribute?
/Users/nickmerwin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/request_body_diff.rb:20: warning: private attribute?
/Users/nickmerwin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/request_execution_verifier.rb:41: warning: assigned but unused variable - is_negated
/Users/nickmerwin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/request_execution_verifier.rb:45: warning: assigned but unused variable - is_negated
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
.............................................

Finished in 2.07 seconds (files took 0.68495 seconds to load)
45 examples, 0 failures

/Users/nickmerwin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/simplecov-0.11.0/lib/simplecov.rb:56: warning: instance variable @track_files_glob not initialized
Coverage report generated for RSpec to /Users/nickmerwin/www/coveralls-ruby/coverage. 286 / 308 LOC (92.86%) covered.
```

Thanks!

**Comment by mlarraz** [comment]
Those look like warnings in the gems themselves. Updating to the latest webmock fixes at least a few of them.

**Comment by nickmerwin** [comment]
@mlarraz ok down to 2 warnings, looks better. Thanks!

**Pull request merged**
