### PR TITLE
Update simplecov dependency to 0.14.1

### LINKED ISSUE #116: Coveralls and Ruby 2.4
`coveralls 0.8.19` depends on `simplecov ~> 0.12.0`.

`simplecov 0.12.0` raises deprecation warnings when running under Ruby 2.4. This was fixed today with the new `0.13.0` release.

I would appreciate if you update coveralls to depend on `simplecov ~> 0.13.0`. That would allow `coveralls` to run under Ruby 2.4 without deprecation warnings.

If you want me to submit a PR for this change, please ping me.

### PR DESCRIPTION
**Pull request by tagliala**
Fix #116

### CODE REVIEW

**Comment by junaruga** [comment]
I also want to use `simplecov` 0.13.0 for Ruby 2.4.0 compatibility.
`simplecov` 0.12.0 stopped by core dump for `cucumber` Travis Ruby 2.4.0 test.
https://travis-ci.org/cucumber/cucumber-ruby-core/jobs/197417468

**Comment by tagliala** [comment]
@junaruga 

Hi, I don't understand if this PR is ok and my branch fixes your issue or if this doesn't work and I should do something else

**Comment by junaruga** [comment]
@tagliala thanks for your quick replying.
ok, if your branch fixes my issue, I will follow your way.

As an actual circumstance, my issue (`simplecov` 0.12.0's core dump for Ruby 2.4.0 test) has been disappeared [1] after I had updated `simplecov` 0.12.0 to 0.13.0 manually [2] on Travis environment. 

And not only that, `cucumber-ruby` tests also is failed because of `simplecov` 0.12.0 Fixnum/Bignum warning issue on Ruby 2.4.0. [3]

For those reasons, I want to use `coveralls` with `simplecov` 0.13.0.

[1] https://github.com/cucumber/cucumber-ruby-core/pull/120
[2] https://github.com/cucumber/cucumber-ruby-core/pull/120/commits/6a7c51cf86fa63252e2f26aef7b358a710199217
[3] https://github.com/cucumber/cucumber-ruby/pull/1075

**Comment by captn3m0** [comment]
@tagliala the PR looks good to me. Can we get this merged? Right now we're allowing build-failures on travis for 2.4.0 because of this

**Comment by tagliala** [comment]
Hi,

I'm [not going to use](https://bugs.ruby-lang.org/issues/13107) Ruby 2.4.0 at all, but it would be nice to switch to 2.4.1 asap.

Is there something I can do to speed up things?

**Comment by ajm188** [comment]
@tagliala what's the ETA on merging this? Not sure what's blocking...

**Comment by tagliala** [comment]
There is a failing spec with the just released simplecov 0.14.0

```
  1) Coveralls::SimpleCov::Formatter#format #get_source_files nils the skipped lines
     Failure/Error: source_file[:coverage].should eq [nil, 1, 1, 1, nil, 0, 1, nil, nil, nil]
     
       expected: [nil, 1, 1, 1, nil, 0, 1, nil, nil, nil]
            got: [nil, 1, 1, 1, nil, 0, nil, nil, nil, nil, nil]
     
       (compared using ==)
     # ./spec/coveralls/simplecov_spec.rb:79:in `block (4 levels) in <top (required)>'
```

I'm trying to take a look

**Comment by tagliala** [comment]
Offending commit: https://github.com/colszowka/simplecov/commit/d4756e4e9bf20fb1a5a81475d3f22dcdeb7f46a8

Please let me know what is the expected behavior which we would expect from this change

**Comment by tagliala** [comment]
I think the new behaviour is the correct one, I will fix specs accordingly

Image (before and after)

image

**Comment by tagliala** [comment]
Done.

Looks good to me 👍

**Comment by tagliala** [comment]
Updated to 0.14.1

**Comment by bogdanRada** [comment]
i don't see this merged in master branch . Why was this marked as being merged if is not? 
I really need this functionality too. Any help appreciated.

**Comment by junaruga** [comment]
Hi @tagliala 

> I'm not going to use Ruby 2.4.0 at all, but it would be nice to switch my applications to 2.4.1 asap.

Ruby 2.4.1 was released as a information.
https://www.ruby-lang.org/en/news/2017/03/22/ruby-2-4-1-released/

**Comment by tagliala** [comment]
@junaruga thanks!

I was checking Ruby's website every day. I will try this release and I hope I will not face that issue again

**Comment by tagliala** [comment]
Tested against 2.4.1

All green on travis: https://travis-ci.org/lemurheavy/coveralls-ruby/builds/214231009, I hope this could be merged

Ref: https://github.com/travis-ci/travis-ci/issues/7512

**Comment by junaruga** [comment]
Good day, @nickmerwin or other maintainers.
You may be busy. But can you answer on this PR?
If you have no time for the gem package.
I think that it's time to add co-maintainer newly.

**Comment by timbru31** [comment]
This is blocking my project, too :(

**Comment by ajm188** [comment]
Regarding @junaruga 's comment, I'm happy to come on as a co-maintainer to help out, if you're interested, @nickmerwin

**Comment by tagliala** [comment]
Update: Test against Ruby 2.3.4

Fails because of Travis CI: https://github.com/travis-ci/travis-ci/issues/7535

**Comment by ajm188** [comment]
@tagliala looks like we're good to merge?

**Comment by tagliala** [comment]
@ajm188 Travis is still not able to test against Ruby 2.3.4, but I'm pretty confident that everything would be fine.

PS: I cannot merge, I'm a contributor because I did a couple of PR in the past, but I'm not a member of this repo.

**Comment by nickmerwin** [comment]
Alright this looks great, thank you @tagliala!

@ajm188 I'll contact you over email to talk maintainer-ship 👍

**Comment by tagliala** [comment]
@nickmerwin could you please restart the build at https://travis-ci.org/lemurheavy/coveralls-ruby ? 2.3.4 is now available on Travis

**Comment by nickmerwin** [comment]
@tagliala done -- we're green!

**Comment by tagliala** [comment]
Thanks for the merge and the release, my OCD is now satisfied with all those green lights :)

image

**Pull request merged**
