### PR TITLE
Relax thor dependency

### PR DESCRIPTION
**Pull request by y-yagi**
For allow to use thor v0.20.0.
https://github.com/erikhuda/thor/blob/master/CHANGELOG.md#0200

### CODE REVIEW

**Comment by ninoseki** [comment]
I have Ruby projects that use Coveralls and Thor but because of `'thor', '~> 0.19.4’` restriction,  I cannot use the latest version of Thor.
This PR solve that issue. So It would be great if you merge this PR.

**Comment by groot-gu** [comment]
+1

**Comment by y-yagi** [comment]
Rails 6.0.0 requires thor `>= 0.20.3`. 
https://github.com/rails/rails/blob/3c6cfdf7adf4848976b7f425b1811d447b130f6a/railties/railties.gemspec#L40 

This means that coveralls-ruby can not be used with Rails 6.0.0 unless this PR is merged. 
Can anyone check this PR?

**Comment by y-yagi** [comment]
Just a friendly ping

**Comment by shanecav84** [comment]
@nickmerwin

**Comment by nickmerwin** [comment]
Hi @y-yagi and @shanecav84 apologies for the delay -- could you please have a look at the Travis failures?

https://travis-ci.org/lemurheavy/coveralls-ruby/jobs/481620882

**Comment by shanecav84** [comment]
Thanks, @nickmerwin!

**Comment by y-yagi** [comment]
Thanks, @nickmerwin!

**Pull request merged**
