### PR TITLE
Update to simplecov 0.10

### PR DESCRIPTION
**Pull request by nTraum**
Changelog can be found here: https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md#0100-2015-04-18-changes

No breaking changes as far as I can see.

### CODE REVIEW

**Comment by tagliala** [comment]
:+1:

**Comment by sferik** [comment]
Should be good. I’ve also included this change in #83, so you could also just merge that.

**Comment by nickmerwin** [comment]
Thanks @nTraum, this change came through on @sferik's PR.

Releasing a new version now. Cheers!

**Comment by nTraum** [comment]
Thanks for updating! :)

**Comment by tagliala** [comment]
thanks!

**Pull request closed without merging**
